### ISSUE TITLE
CDCE906 Read Error

### ISSUE THREAD

**Issue by alex-dewar** [newaetech/cw310-bergen-board#9]
Latest firmware (1.3.0) seems to have broken I2C:

```python
>>> target = cw.target(None, cw.targets.CW310)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jw/projects/chipwhisperer/software/chipwhisperer/__init__.py", line 422, in target
    rtn.con(scope, **kwargs)
  File "/home/jw/projects/chipwhisperer/software/chipwhisperer/capture/targets/_base.py", line 65, in con
    self._con(scope, **kwargs)
  File "/home/jw/projects/chipwhisperer/software/chipwhisperer/capture/targets/CW310.py", line 143, in _con
    self.pll.cdce906init()
  File "/home/jw/projects/chipwhisperer/software/chipwhisperer/hardware/naeusb/pll_cdce906.py", line 265, in cdce906init
    self.outputUpdateOutputs(0)
  File "/home/jw/projects/chipwhisperer/software/chipwhisperer/hardware/naeusb/pll_cdce906.py", line 94, in outputUpdateOutputs
    pll_enabled = self.pll_outenable_get(outnum)
  File "/home/jw/projects/chipwhisperer/software/chipwhisperer/hardware/naeusb/pll_cdce906.py", line 140, in pll_outenable_get
    data = self.cdce906read(19 + outpin)
  File "/home/jw/projects/chipwhisperer/software/chipwhisperer/hardware/naeusb/pll_cdce906.py", line 255, in cdce906read
    raise IOError("CDCE906 Read Error, response = %d" % resp[0])
OSError: CDCE906 Read Error, response = 3
```

This works on earlier versions (1.2.0). Presumably something was changed when adding CW340 support that broke I2C.

**Comment by alex-dewar** [comment]
Hopefully fixed by 76231fd01b90df4d3991aaca317a41fce6d278d3
